### ISSUE TITLE
I used SpringCloudDubbo in EDAS, but failed

### ISSUE THREAD

**Issue by halower** [spring-cloud-incubator/spring-cloud-alibaba#460]
@I used SpringCloudDubbo in EDAS, but failed
我在EDAS中使用SpringCloudDubbo，但是失败了 @mercyblitz
```
 spring:
  cloud:
    alicloud:
       ans:
        server-list: 127.0.0.1
        server-port: 8080
      edas:
        enabled: true
  profiles: eads 
```
